# Generated by Django 5.1.5 on 2025-12-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zserver", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Session",
        ),
    ]
