# Step 1: Use the official Python image as the base image
FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Install Python dependencies
COPY requirements/development.txt requirements/development.txt
RUN pip3 install --upgrade pip && \
    pip3 install -r requirements/development.txt

# Copy project files
COPY . .

# setup django project
RUN python manage.py migrate

# add port 8000
EXPOSE 8000

# Keep the container running
CMD ["sleep", "infinity"]
